# Emperical Probability of Up Move given Create/Join

In [32]:
#Get CJ Flagger df

import sys
sys.path.insert(0, "../Helper_Input")
from iex_helper import * #imports stock_data class from iex_helper.py
import time
#######################################################
start = time.time()
quotes = '../Training_Files/AAPL_train.csv' #
q = pd.read_csv(quotes,low_memory = False)
AAPL_QW = Quote_Wrangler(quotes) #initiate class
from IPython.display import display
from IPython.display import Markdown
end = time.time()
print('Time to Completion: ', end-start, " seconds")

NBBO = AAPL_QW.NB_master

Time to Completion:  6.531626462936401  seconds

In [82]:
NBB_all = AAPL_QW.cj_flagger(nbb_flag=True)
NBO_all = AAPL_QW.cj_flagger(nbb_flag=False)
NBB_all.head(15)
NBBO_cj_Master = NBB_all.append(NBO_all)
NBBO_cj_Master = NBBO_cj_Master.sort_values(by = 'Time')
NBBO_cj_Master.head(15)

../Helper_Input\iex_helper.py:267: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  nb_df['Creates'] = create_master
../Helper_Input\iex_helper.py:268: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  nb_df['Joins'] = join_master

,Time,B_Exchanges,B_Vol_Ex,B_Vol_Tot,Bid,Ask,A_Vol_Tot,A_Vol_Ex,A_Exchanges,Flag,Spread,Mid,Weighted Avg Mid,Creates,Joins
0,09:00:06.476309,[P],[1.0],1.0,172.77,172.87,1.0,[1.0],[P],NBB,0.10,172.820,172.820000,,
1,09:00:22.725508,[P],[2.0],2.0,172.78,172.87,1.0,[1.0],[P],NBB,0.09,172.825,172.810000,,
2,09:00:22.763127,[P],[2.0],2.0,172.78,172.80,39.0,[39.0],[K],NBO,0.02,172.790,172.799024,,
3,09:00:23.331916,[P],[2.0],2.0,172.78,172.80,38.0,[38.0],[K],NBO,0.02,172.790,172.799000,,
4,09:00:47.518971,[P],[2.0],2.0,172.78,172.80,33.0,[33.0],[K],NBO,0.02,172.790,172.798857,,
5,09:00:48.930833,[P],[1.0],1.0,172.77,172.80,33.0,[33.0],[K],NBB,0.03,172.785,172.799118,,
6,09:00:48.950897,[P],[1.0],1.0,172.77,172.80,32.0,[32.0],[K],NBO,0.03,172.785,172.799091,,
7,09:00:50.328567,[P],[1.0],1.0,172.77,172.80,28.0,[28.0],[K],NBO,0.03,172.785,172.798966,,
8,09:01:01.584113,[P],[1.0],1.0,172.77,172.80,21.0,[21.0],[K],NBO,0.03,172.785,172.798636,,
9,09:01:13.584744,[P],[1.0],1.0,172.77,172.80,18.0,[18.0],[K],NBO,0.03,172.785,172.798421,,
10,09:01:13.585644,[P],[1.0],1.0,172.77,172.82,1.0,[1.0],[K],NBO,0.05,172.795,172.795000,,
11,09:01:13.585768,[Y],[1.0],1.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.800000,,
12,09:01:13.585769,"[K, Y]","[1.0, 1.0]",2.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.793333,{'K': 1.0},
13,09:01:13.585790,"[J, K, Y]","[1.0, 1.0, 1.0]",3.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.790000,{'J': 1.0},
14,09:01:13.585809,"[J, K, Y, Z]","[1.0, 1.0, 1.0, 1.0]",4.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.788000,{'Z': 1.0},

Now, using NBO_all or NBB_all, we find the next unique mid, and save this as its own column. The functionality for this is found as seperate helper functions in iex_helper

In [83]:
NBBO = get_next_mid(NBBO_cj_Master)
NBBO.head(15)

,Time,B_Exchanges,B_Vol_Ex,B_Vol_Tot,Bid,Ask,A_Vol_Tot,A_Vol_Ex,A_Exchanges,Flag,Spread,Mid,Weighted Avg Mid,Creates,Joins,Mid_Next
0,09:00:06.476309,[P],[1.0],1.0,172.77,172.87,1.0,[1.0],[P],NBB,0.10,172.820,172.820000,,,172.825
1,09:00:22.725508,[P],[2.0],2.0,172.78,172.87,1.0,[1.0],[P],NBB,0.09,172.825,172.810000,,,172.790
2,09:00:22.763127,[P],[2.0],2.0,172.78,172.80,39.0,[39.0],[K],NBO,0.02,172.790,172.799024,,,172.785
3,09:00:23.331916,[P],[2.0],2.0,172.78,172.80,38.0,[38.0],[K],NBO,0.02,172.790,172.799000,,,172.785
4,09:00:47.518971,[P],[2.0],2.0,172.78,172.80,33.0,[33.0],[K],NBO,0.02,172.790,172.798857,,,172.785
5,09:00:48.930833,[P],[1.0],1.0,172.77,172.80,33.0,[33.0],[K],NBB,0.03,172.785,172.799118,,,172.795
6,09:00:48.950897,[P],[1.0],1.0,172.77,172.80,32.0,[32.0],[K],NBO,0.03,172.785,172.799091,,,172.795
7,09:00:50.328567,[P],[1.0],1.0,172.77,172.80,28.0,[28.0],[K],NBO,0.03,172.785,172.798966,,,172.795
8,09:01:01.584113,[P],[1.0],1.0,172.77,172.80,21.0,[21.0],[K],NBO,0.03,172.785,172.798636,,,172.795
9,09:01:13.584744,[P],[1.0],1.0,172.77,172.80,18.0,[18.0],[K],NBO,0.03,172.785,172.798421,,,172.795
10,09:01:13.585644,[P],[1.0],1.0,172.77,172.82,1.0,[1.0],[K],NBO,0.05,172.795,172.795000,,,172.800
11,09:01:13.585768,[Y],[1.0],1.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.800000,,,172.795
12,09:01:13.585769,"[K, Y]","[1.0, 1.0]",2.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.793333,{'K': 1.0},,172.795
13,09:01:13.585790,"[J, K, Y]","[1.0, 1.0, 1.0]",3.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.790000,{'J': 1.0},,172.795
14,09:01:13.585809,"[J, K, Y, Z]","[1.0, 1.0, 1.0, 1.0]",4.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.788000,{'Z': 1.0},,172.795

Compute Difference column, as this will be usefull in the next steps

In [84]:
NBBO['Mid_Change'] = NBBO.Mid_Next - NBBO.Mid
#This is the last step before function two cells below

Now, we want to splice this by creates/joins AND by exchange. We start with an example - Exchange T Creates

In [87]:
#First Isolate Exchange
P_flag = NBBO.B_Exchanges.apply(lambda x :'P' in x)
BBO_P = NBBO.copy()
BBO_P['Ex_Flag'] = P_flag
BBO_P = BBO_P[BBO_P.Ex_Flag == True]
display(BBO_P.head(20))
print('\n')
#Next Isolate Creates/Joins
BBO_P_Create = BBO_P[BBO_P.Creates != '']
BBO_P_Join = BBO_P[BBO_P.Joins != '']
display(Markdown('BBO P Exchange, Joins'))
display(BBO_P_Join.head())

,Time,B_Exchanges,B_Vol_Ex,B_Vol_Tot,Bid,Ask,A_Vol_Tot,A_Vol_Ex,A_Exchanges,Flag,Spread,Mid,Weighted Avg Mid,Creates,Joins,Mid_Next,Mid_Change,Ex_Flag
0,09:00:06.476309,[P],[1.0],1.0,172.77,172.87,1.0,[1.0],[P],NBB,0.10,172.820,172.820000,,,172.825,0.005,True
1,09:00:22.725508,[P],[2.0],2.0,172.78,172.87,1.0,[1.0],[P],NBB,0.09,172.825,172.810000,,,172.790,-0.035,True
2,09:00:22.763127,[P],[2.0],2.0,172.78,172.80,39.0,[39.0],[K],NBO,0.02,172.790,172.799024,,,172.785,-0.005,True
3,09:00:23.331916,[P],[2.0],2.0,172.78,172.80,38.0,[38.0],[K],NBO,0.02,172.790,172.799000,,,172.785,-0.005,True
4,09:00:47.518971,[P],[2.0],2.0,172.78,172.80,33.0,[33.0],[K],NBO,0.02,172.790,172.798857,,,172.785,-0.005,True
5,09:00:48.930833,[P],[1.0],1.0,172.77,172.80,33.0,[33.0],[K],NBB,0.03,172.785,172.799118,,,172.795,0.010,True
6,09:00:48.950897,[P],[1.0],1.0,172.77,172.80,32.0,[32.0],[K],NBO,0.03,172.785,172.799091,,,172.795,0.010,True
7,09:00:50.328567,[P],[1.0],1.0,172.77,172.80,28.0,[28.0],[K],NBO,0.03,172.785,172.798966,,,172.795,0.010,True
8,09:01:01.584113,[P],[1.0],1.0,172.77,172.80,21.0,[21.0],[K],NBO,0.03,172.785,172.798636,,,172.795,0.010,True
9,09:01:13.584744,[P],[1.0],1.0,172.77,172.80,18.0,[18.0],[K],NBO,0.03,172.785,172.798421,,,172.795,0.010,True
10,09:01:13.585644,[P],[1.0],1.0,172.77,172.82,1.0,[1.0],[K],NBO,0.05,172.795,172.795000,,,172.800,0.005,True
15,09:01:13.586037,"[J, K, P, Y, Z]","[1.0, 1.0, 1.0, 1.0, 1.0]",5.0,172.78,172.82,1.0,[1.0],[K],NBB,0.04,172.800,172.786667,{'P': 1.0},,172.795,-0.005,True
16,09:01:13.615625,"[J, K, P, Y, Z]","[1.0, 1.0, 1.0, 1.0, 1.0]",5.0,172.78,172.81,2.0,[2.0],[Q],NBO,0.03,172.795,172.788571,,,172.790,-0.005,True
17,09:01:13.615661,"[J, K, P, Y, Z]","[1.0, 1.0, 1.0, 1.0, 1.0]",5.0,172.78,172.81,4.0,[4.0],[Q],NBO,0.03,172.795,172.793333,,{'Q': 2.0},172.790,-0.005,True
18,09:01:13.615745,"[J, K, P, Z]","[1.0, 1.0, 1.0, 1.0]",4.0,172.78,172.81,4.0,[4.0],[Q],NBB,0.03,172.795,172.795000,,,172.790,-0.005,True
19,09:01:13.615749,"[J, K, P]","[1.0, 1.0, 1.0]",3.0,172.78,172.81,4.0,[4.0],[Q],NBB,0.03,172.795,172.797143,,,172.790,-0.005,True
20,09:01:13.615751,"[K, P]","[1.0, 1.0]",2.0,172.78,172.81,4.0,[4.0],[Q],NBB,0.03,172.795,172.800000,,,172.790,-0.005,True
21,09:01:13.615752,[P],[1.0],1.0,172.78,172.81,4.0,[4.0],[Q],NBB,0.03,172.795,172.804000,,,172.790,-0.005,True
22,09:01:13.616029,[P],[1.0],1.0,172.77,172.81,4.0,[4.0],[Q],NBB,0.04,172.790,172.802000,,,172.795,0.005,True
23,09:01:13.715709,[P],[1.0],1.0,172.77,172.81,2.0,[2.0],[Q],NBO,0.04,172.790,172.796667,,,172.795,0.005,True

BBO P Exchange, Joins

,Time,B_Exchanges,B_Vol_Ex,B_Vol_Tot,Bid,Ask,A_Vol_Tot,A_Vol_Ex,A_Exchanges,Flag,Spread,Mid,Weighted Avg Mid,Creates,Joins,Mid_Next,Mid_Change,Ex_Flag
17,09:01:13.615661,"[J, K, P, Y, Z]","[1.0, 1.0, 1.0, 1.0, 1.0]",5.0,172.78,172.81,4.0,[4.0],[Q],NBO,0.03,172.795,172.793333,,{'Q': 2.0},172.790,-0.005,True
31,09:01:57.401516,[P],[1.0],1.0,172.77,172.81,4.0,"[1.0, 3.0]","[K, Q]",NBO,0.04,172.790,172.802000,,{'Q': 2.0},172.785,-0.005,True
35,09:02:20.868782,"[K, P]","[1.0, 3.0]",4.0,172.77,172.81,1.0,[1.0],[K],NBB,0.04,172.790,172.778000,,{'P': 2.0},172.785,-0.005,True
62,09:05:35.843400,"[K, P]","[2.0, 3.0]",5.0,172.82,172.87,6.0,"[4.0, 2.0]","[K, P]",NBO,0.05,172.845,172.847273,,{'P': 1.0},172.850,0.005,True
66,09:06:33.785614,"[K, P]","[2.0, 2.0]",4.0,172.82,172.87,5.0,"[3.0, 2.0]","[K, P]",NBO,0.05,172.845,172.847778,,{'P': 1.0},172.850,0.005,True

Now that we have isolated exchange P, Joins, we can find the empirical probability of an up move

In [89]:
up_count = sum(np.array(BBO_P_Join.Mid_Change > 0))
prob = up_count/len(BBO_P_Join)
print("Probability of an Up Move: ", prob)

Probability of an Up Move:  0.4780266343825666

Using this method, we can iterate though all exchanges for Creates or Joins and find the emperical prob

In [96]:
exch = list(AAPL_QW.exchange_map.keys())
def prob_finder(NBX,exch):
    """
    NBX should be NBBO with cj and mid_next
    """
    prob_matrix = np.empty([len(exch),4])
    NBX_BB = NBX[NBX.Flag == 'NBB']
    NBX_BO = NBX[NBX.Flag == 'NBO']
    for i in range(len(exch)):
        ex = exch[i]
        NBX_BB_ex = NBX_BB.copy()
        NBX_BO_ex = NBX_BO.copy()
        
        NBX_BB_ex['Ex_Flag'] =  NBX_BB_ex.B_Exchanges.apply(lambda x :ex in x)
        NBX_BB_ex = NBX_BB_ex[NBX_BB_ex.Ex_Flag == True]

        NBX_BO_ex['Ex_Flag'] =  NBX_BO_ex.A_Exchanges.apply(lambda x :ex in x)
        NBX_BO_ex = NBX_BO_ex[NBX_BO_ex.Ex_Flag == True]
            
        NBX_BB_ex_C = NBX_BB_ex[NBX_BB_ex.Creates != '']
        NBX_BB_ex_J = NBX_BB_ex[NBX_BB_ex.Joins != '']

        NBX_BO_ex_C = NBX_BO_ex[NBX_BO_ex.Creates != '']
        NBX_BO_ex_J = NBX_BO_ex[NBX_BO_ex.Joins != '']
        
        try:
            prob_BB_c = sum(np.array(NBX_BB_ex_C.Mid_Change > 0))/len(NBX_BB_ex_C)
        except:
            prob_BB_c = 0
        try:
            prob_BB_j = sum(np.array(NBX_BB_ex_J.Mid_Change > 0))/len(NBX_BB_ex_J)
        except:
            prob_BB_j = 0
        try:
            prob_BO_c = sum(np.array(NBX_BO_ex_C.Mid_Change > 0))/len(NBX_BO_ex_C)
        except:
            prob_BO_c = 0
        try:
            prob_BO_j = sum(np.array(NBX_BO_ex_J.Mid_Change > 0))/len(NBX_BO_ex_J)
        except:
            prob_BO_j = 0
            
            
        prob_matrix[i,0] = prob_BB_c
        prob_matrix[i,1] = prob_BB_j
        prob_matrix[i,2] = prob_BO_c
        prob_matrix[i,3] = prob_BO_j
    prob_df = pd.DataFrame(prob_matrix)
    prob_df.index = exch
    prob_df.columns = ['Best_Bid_Creates','Best_Bid_Joins','Best_Offer_Creates','Best_Offer_Joins']
    return prob_df

NBBO_probs = prob_finder(NBBO,exch)

# NBO_probs[(NBO_probs.Creates > 0) & (NBO_probs.Joins > 0)]

In [97]:
NBBO_probs

   Best_Bid_Creates  Best_Bid_Joins  Best_Offer_Creates  Best_Offer_Joins
A          0.800000        0.848837            0.377049          0.214286
B          0.685283        0.742620            0.274375          0.196789
C          0.000000        0.000000            0.000000          0.000000
D          0.000000        0.000000            0.000000          0.000000
I          0.000000        0.000000            0.000000          0.000000
J          0.715175        0.755956            0.226006          0.152918
K          0.631477        0.684488            0.335491          0.236039
M          0.400000        0.750000            0.333333          0.000000
N          0.000000        0.000000            0.000000          0.000000
P          0.637770        0.694527            0.340125          0.234769
S          0.000000        0.000000            0.000000          0.000000
T          0.000000        0.000000            0.000000          0.000000
Q          0.653161        0.697682            0.326277          0.241246
V          0.641318        0.763810            0.331210          0.248408
W          0.000000        0.000000            0.000000          0.000000
X          0.759690        0.779762            0.284615          0.178354
Y          0.687419        0.733773            0.239642          0.180929
Z          0.659708        0.700836            0.311322          0.228766

OUTLINE TO PUT INTO ALGORITHM
1. NBBO w/o CJ
2. NBO and NBB using CJ Function
3. Recombine and sort by time -> NBBO w/ CJ
4. Get Mid_Next columns
5. Feed into prob finder function